export const destinations = [
  /* --- Africa --- */
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina_Faso",
  "Burundi",
  "Cameroon",
  "Cape_Verde",
  "Central_African_Republic",
  "Chad",
  "Comoros",
  "Republic_of_the_Congo",
  "Democratic_Republic_of_the_Congo",
  "Djibouti",
  "Egypt",
  "Equatorial_Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Ivory_Coast",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Rwanda",
  "São_Tomé_and_Príncipe",
  "Senegal",
  "Seychelles",
  "Sierra_Leone",
  "Somalia",
  "Somaliland",
  "South_Africa",
  "South_Sudan",
  "Sudan",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Western_Sahara",
  "Zambia",
  "Zimbabwe",

  /* --- Americas --- */
  "Antigua_and_Barbuda",
  "Argentina",
  "Aruba",
  "Bahamas",
  "Barbados",
  "Belize",
  "Bermuda",
  "Bolivia",
  "Brazil",
  "British_Virgin_Islands",
  "Canada",
  "Cayman_Islands",
  "Chile",
  "Colombia",
  "Costa_Rica",
  "Cuba",
  "Curaçao",
  "Dominica",
  "Dominican_Republic",
  "Ecuador",
  "El_Salvador",
  "Falkland_Islands",
  "Greenland",
  "Grenada",
  "Guatemala",
  "Guyana",
  "Haiti",
  "Honduras",
  "Jamaica",
  "Mexico",
  "Nicaragua",
  "Panama",
  "Paraguay",
  "Peru",
  "Puerto_Rico",
  "Saint_Kitts_and_Nevis",
  "Saint_Lucia",
  "Saint_Vincent_and_the_Grenadines",
  "Suriname",
  "Trinidad_and_Tobago",
  "Turks_and_Caicos_Islands",
  "United_States_of_America",
  "Uruguay",
  "United_States_Virgin_Islands",
  "Venezuela",

  /* --- Asia Pacific --- */
  "Afghanistan",
  "Australia",
  "Bangladesh",
  "Bhutan",
  "Brunei",
  "Cambodia",
  "China",
  "East_Timor",
  "Fiji",
  "Hong_Kong",
  "India",
  "Indonesia",
  "Japan",
  "Kazakhstan",
  "Kiribati",
  "Kyrgyzstan",
  "Laos",
  "Macau",
  "Malaysia",
  "Maldives",
  "Marshall_Islands",
  "Federated_States_of_Micronesia",
  "Mongolia",
  "Myanmar",
  "Nauru",
  "Nepal",
  "New_Caledonia",
  "New_Zealand",
  "North_Korea",
  "Pakistan",
  "Palau",
  "Papua_New_Guinea",
  "Philippines",
  "Samoa",
  "Singapore",
  "Solomon_Islands",
  "South_Korea",
  "Sri_Lanka",
  "Taiwan",
  "Tajikistan",
  "Thailand",
  "Tonga",
  "Turkmenistan",
  "Tuvalu",
  "Uzbekistan",
  "Vanuatu",
  "Vietnam",

  /* --- Europe --- */
  "Albania",
  "Andorra",
  "Armenia",
  "Austria",
  "Azerbaijan",
  "Belarus",
  "Belgium",
  "Bosnia_and_Herzegovina",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czech_Republic",
  "Denmark",
  "Estonia",
  "Faroe_Islands",
  "Finland",
  "France",
  "Georgia_(country)",
  "Germany",
  "Gibraltar",
  "Greece",
  "Hungary",
  "Iceland",
  "Ireland",
  "Isle_of_Man",
  "Italy",
  "Kosovo",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Netherlands",
  "North_Macedonia",
  "Northern_Cyprus",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "San_Marino",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Ukraine",
  "United_Kingdom",
  "Vatican_City",

  /* --- Middle East --- */
  "Bahrain",
  "Iran",
  "Iraq",
  "Israel",
  "Jordan",
  "Kuwait",
  "Lebanon",
  "Oman",
  "Palestinian_Territories",
  "Qatar",
  "Saudi_Arabia",
  "Syria",
  "United_Arab_Emirates",
  "Yemen",
] as const;

export type Destination = (typeof destinations)[number];

const aliases: Record<string, Destination> = {
  georgia: "Georgia_(country)",
  palestine: "Palestinian_Territories",
  "state of palestine": "Palestinian_Territories",
  "west bank and gaza": "Palestinian_Territories",
  micronesia: "Federated_States_of_Micronesia",
  usa: "United_States_of_America",
  us: "United_States_of_America",
  "united states": "United_States_of_America",
  america: "United_States_of_America",
  uk: "United_Kingdom",
  "great britain": "United_Kingdom",
  britain: "United_Kingdom",
  england: "United_Kingdom",
  uae: "United_Arab_Emirates",
  dubai: "United_Arab_Emirates",
  holland: "Netherlands",
  czechia: "Czech_Republic",
  burma: "Myanmar",
  korea: "South_Korea",
  ceylon: "Sri_Lanka",
  lanka: "Sri_Lanka",
  bosnia: "Bosnia_and_Herzegovina",
};

function normalise(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[_+]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

const lookup: ReadonlyMap<string, Destination> = new Map<string, Destination>([
  ...destinations.map(
    (title) => [normalise(title), title] as [string, Destination],
  ),
  ...Object.entries(aliases),
]);

export function resolveDestination(value: string): Destination | null {
  if (typeof value !== "string" || value.length > 80) return null;
  return lookup.get(normalise(value)) ?? null;
}

export const isKnownDestination = (value: string): boolean =>
  resolveDestination(value) !== null;

export const destinationOptions = destinations.map((title) => ({
  value: title,
  label: title.replace(/_/g, " "),
}));
